#!/bin/bash
# arguments: 
# 1) single cell as a .bam file
# 2) mutation list (SNPs only) generated by Mutect2 as a .csv

singularity exec -B $PWD step8_CorrectUMIs.sif \
    /Step8_UMIcorrection.sh BL5512_CCTTTCTTCATGTCCC-1.bam mutations_cell.csv
        
# Check intermediate and output files:
cat FilteredMutations
cat meta.tsv
cat reads.tsv
